version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: fnr-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: fnr_db
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
