export const ITEM_KEYS = {
  ID: 'id',
  GROUP: 'group',
  NAME: 'name',
  CATEGORY: 'category',
  MODEL_SERIAL_NUMBER: 'modelSerialNumber',
  STATUS: 'status',
  OIS_QUOTE: 'oisquote',
  OUR_QUOTE: 'ourquote',
  DIFFERENCE: 'difference',
  RECEIPT_PHOTO_URL: 'receiptPhotoUrl',
  DATE_CREATED: 'dateCreated',
  AMOUNT: 'amount',
  ACTIONS: 'actions',
} as const;
