import { Item } from './item';
import { ItemCategory } from './itemCategories';
import { ItemStatus } from './ItemStatus';

export const randomItemsData: Item[] = [
  {
    id: 1,
    localId: 1,
    name: 'Laptop',
    category: null, // Test item with null category
    modelSerialNumber: 'LT-2022-XPS15',
    dateCreated: new Date('2022-07-15'),
    itemStatus: ItemStatus.RS,
    roomCategory: null,
    insuredsQuote: 2000,
    ourQuote: 1800,
    receiptPhotoUrl: 'https://example.com/receipts/laptop2022.jpg',
    ourQuoteProof: null,
  },
  {
    id: 2,
    localId: 2,
    name: 'Office Chair',
    category: ItemCategory.FURNITURE,
    modelSerialNumber: 'OC-2021-ERGOX',
    dateCreated: new Date('2022-07-16'),
    itemStatus: ItemStatus.NR,
    roomCategory: null,
    insuredsQuote: 450,
    ourQuote: 400,
    receiptPhotoUrl: null,
    ourQuoteProof: null,
  },
  {
    id: 3,
    localId: 3,
    name: 'Smartphone',
    category: ItemCategory.ELECTRONICS,
    modelSerialNumber: 'SP-2023-GALX',
    dateCreated: new Date('2022-07-17'),
    itemStatus: ItemStatus.RS,
    roomCategory: null,
    insuredsQuote: 1100,
    ourQuote: 1000,
    receiptPhotoUrl: 'https://example.com/receipts/smartphone2023.jpg',
    ourQuoteProof: null,
  },
  {
    id: 4,
    localId: 4,
    name: 'Desk',
    category: ItemCategory.FURNITURE,
    modelSerialNumber: 'DK-2020-STAND',
    dateCreated: new Date('2022-07-18'),
    itemStatus: ItemStatus.NR,
    roomCategory: null,
    insuredsQuote: 600,
    ourQuote: 600,
    receiptPhotoUrl: null,
    ourQuoteProof: null,
  },
  {
    id: 5,
    localId: 5,
    name: 'Monitor',
    category: ItemCategory.ELECTRONICS,
    modelSerialNumber: 'MN-2022-4KHD',
    dateCreated: new Date('2022-07-19'),
    itemStatus: ItemStatus.RS,
    roomCategory: null,
    insuredsQuote: 400,
    ourQuote: 350,
    receiptPhotoUrl: 'https://example.com/receipts/monitor2022.jpg',
    ourQuoteProof: null,
  },
  {
    id: 6,
    localId: 6,
    name: 'Printer',
    category: ItemCategory.ELECTRONICS,
    modelSerialNumber: 'PR-2021-LSRJ',
    dateCreated: new Date('2022-07-20'),
    itemStatus: ItemStatus.VPOL,
    roomCategory: null,
    insuredsQuote: 350,
    ourQuote: 300,
    receiptPhotoUrl: null,
    ourQuoteProof: null,
  },
  {
    id: 7,
    localId: 7,
    name: 'Filing Cabinet',
    category: ItemCategory.FURNITURE,
    modelSerialNumber: 'FC-2019-METAL4',
    dateCreated: new Date('2022-07-21'),
    itemStatus: ItemStatus.NR,
    roomCategory: null,
    insuredsQuote: 220,
    ourQuote: 200,
    receiptPhotoUrl: null,
    ourQuoteProof: null,
  },
  {
    id: 8,
    localId: 8,
    name: 'Software License',
    category: ItemCategory.OTHER,
    modelSerialNumber: 'SL-2023-OFFIC',
    dateCreated: new Date('2022-07-22'),
    itemStatus: ItemStatus.RS,
    roomCategory: null,
    insuredsQuote: 160,
    ourQuote: 150,
    receiptPhotoUrl: 'https://example.com/receipts/software2023.jpg',
    ourQuoteProof: null,
  },
  {
    id: 9,
    localId: 9,
    name: 'Projector',
    category: ItemCategory.ELECTRONICS,
    modelSerialNumber: 'PJ-2020-4KHD',
    dateCreated: new Date('2022-07-23'),
    itemStatus: ItemStatus.NR,
    roomCategory: null,
    insuredsQuote: 850,
    ourQuote: 800,
    receiptPhotoUrl: null,
    ourQuoteProof: null,
  },
  {
    id: 10,
    localId: 10,
    name: 'Whiteboard',
    category: ItemCategory.SUPPLIES,
    modelSerialNumber: 'WB-2022-MAGN',
    dateCreated: new Date('2022-07-24'),
    itemStatus: ItemStatus.RS,
    roomCategory: null,
    insuredsQuote: 100,
    ourQuote: 90,
    receiptPhotoUrl: 'https://example.com/receipts/whiteboard2022.jpg',
    ourQuoteProof: null,
  },
];
