import { Item } from './item';
import { ItemCategory } from './itemCategories';

export const randomItemsData: Item[] = [
  {
    id: 1,
    name: 'Laptop',
    category: null, // Test item with null category
    modelSerialNumber: 'LT-2022-XPS15',
    dateCreated: new Date('2022-07-15'),
    status: 'RS',
    group: '',
    insuredsQuote: 2000,
    ourquote: 1800,
    receiptPhotoUrl: 'https://example.com/receipts/laptop2022.jpg',
    ourquoteLink: null,
  },
  {
    id: 2,
    name: 'Office Chair',
    category: ItemCategory.Furniture,
    modelSerialNumber: 'OC-2021-ERGOX',
    dateCreated: new Date('2022-07-16'),
    status: 'NR',
    group: '',
    insuredsQuote: 450,
    ourquote: 400,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 3,
    name: 'Smartphone',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'SP-2023-GALX',
    dateCreated: new Date('2022-07-17'),
    status: 'RS',
    group: '',
    insuredsQuote: 1100,
    ourquote: 1000,
    receiptPhotoUrl: 'https://example.com/receipts/smartphone2023.jpg',
    ourquoteLink: null,
  },
  {
    id: 4,
    name: 'Desk',
    category: ItemCategory.Furniture,
    modelSerialNumber: 'DK-2020-STAND',
    dateCreated: new Date('2022-07-18'),
    status: 'NR',
    group: '',
    insuredsQuote: 600,
    ourquote: 600,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 5,
    name: 'Monitor',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'MN-2022-4KHD',
    dateCreated: new Date('2022-07-19'),
    status: 'RS',
    group: '',
    insuredsQuote: 400,
    ourquote: 350,
    receiptPhotoUrl: 'https://example.com/receipts/monitor2022.jpg',
    ourquoteLink: null,
  },
  {
    id: 6,
    name: 'Printer',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'PR-2021-LSRJ',
    dateCreated: new Date('2022-07-20'),
    status: 'VPOL',
    group: '',
    insuredsQuote: 350,
    ourquote: 300,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 7,
    name: 'Filing Cabinet',
    category: ItemCategory.Furniture,
    modelSerialNumber: 'FC-2019-METAL4',
    dateCreated: new Date('2022-07-21'),
    status: 'NR',
    group: '',
    insuredsQuote: 220,
    ourquote: 200,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 8,
    name: 'Software License',
    category: ItemCategory.Other,
    modelSerialNumber: 'SL-2023-OFFIC',
    dateCreated: new Date('2022-07-22'),
    status: 'RS',
    group: '',
    insuredsQuote: 160,
    ourquote: 150,
    receiptPhotoUrl: 'https://example.com/receipts/software2023.jpg',
    ourquoteLink: null,
  },
  {
    id: 9,
    name: 'Projector',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'PJ-2020-4KHD',
    dateCreated: new Date('2022-07-23'),
    status: 'NR',
    group: '',
    insuredsQuote: 850,
    ourquote: 800,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 10,
    name: 'Whiteboard',
    category: ItemCategory.Supplies,
    modelSerialNumber: 'WB-2022-MAGN',
    dateCreated: new Date('2022-07-24'),
    status: 'RS',
    group: '',
    insuredsQuote: 100,
    ourquote: 90,
    receiptPhotoUrl: 'https://example.com/receipts/whiteboard2022.jpg',
    ourquoteLink: null,
  },
  {
    id: 11,
    name: 'Coffee Machine',
    category: ItemCategory.Appliances,
    modelSerialNumber: 'CM-2021-ESPRS',
    dateCreated: new Date('2022-07-25'),
    status: 'NR',
    group: '',
    insuredsQuote: 275,
    ourquote: 250,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 12,
    name: 'External Hard Drive',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'HD-2023-5TB',
    dateCreated: new Date('2022-07-26'),
    status: 'RS',
    group: '',
    insuredsQuote: 140,
    ourquote: 130,
    receiptPhotoUrl: 'https://example.com/receipts/harddrive2023.jpg',
    ourquoteLink: null,
  },
  {
    id: 13,
    name: 'Office Sofa',
    category: ItemCategory.Furniture,
    modelSerialNumber: 'SF-2020-LTHR',
    dateCreated: new Date('2022-07-27'),
    status: 'NR',
    group: '',
    insuredsQuote: 950,
    ourquote: 900,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 14,
    name: 'Wireless Mouse',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'WM-2022-BLTH',
    dateCreated: new Date('2022-07-28'),
    status: 'RS',
    group: '',
    insuredsQuote: 55,
    ourquote: 50,
    receiptPhotoUrl: 'https://example.com/receipts/mouse2022.jpg',
    ourquoteLink: null,
  },
  {
    id: 15,
    name: 'Antivirus Software',
    category: ItemCategory.Other,
    modelSerialNumber: 'AV-2021-PROT',
    dateCreated: new Date('2022-07-29'),
    status: 'VPOL',
    group: '',
    insuredsQuote: 90,
    ourquote: 80,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 16,
    name: 'Conference Table',
    category: ItemCategory.Furniture,
    modelSerialNumber: 'CT-2019-OVAL',
    dateCreated: new Date('2022-07-30'),
    status: 'NR',
    group: '',
    insuredsQuote: 1400,
    ourquote: 1300,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 17,
    name: 'Tablet',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'TB-2023-PRO',
    dateCreated: new Date('2022-07-31'),
    status: 'RS',
    group: '',
    insuredsQuote: 750,
    ourquote: 700,
    receiptPhotoUrl: 'https://example.com/receipts/tablet2023.jpg',
    ourquoteLink: null,
  },
  {
    id: 18,
    name: 'Paper Shredder',
    category: ItemCategory.Supplies,
    modelSerialNumber: 'PS-2020-CROS',
    dateCreated: new Date('2022-08-01'),
    status: 'NR',
    group: '',
    insuredsQuote: 100,
    ourquote: 90,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 19,
    name: 'VPN Service',
    category: ItemCategory.Other,
    modelSerialNumber: 'VPN-2022-SECR',
    dateCreated: new Date('2022-08-02'),
    status: 'RS',
    group: '',
    insuredsQuote: 65,
    ourquote: 60,
    receiptPhotoUrl: 'https://example.com/receipts/vpn2022.jpg',
    ourquoteLink: null,
  },
  {
    id: 20,
    name: 'Ergonomic Keyboard',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'KB-2021-ERGO',
    dateCreated: new Date('2022-08-03'),
    status: 'NR',
    group: '',
    insuredsQuote: 140,
    ourquote: 130,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 21,
    name: 'Desk Lamp',
    category: ItemCategory.Supplies,
    modelSerialNumber: 'DL-2023-LED',
    dateCreated: new Date('2022-08-04'),
    status: 'RS',
    group: '',
    insuredsQuote: 45,
    ourquote: 40,
    receiptPhotoUrl: 'https://example.com/receipts/lamp2023.jpg',
    ourquoteLink: null,
  },
  {
    id: 22,
    name: 'Microwave',
    category: ItemCategory.Appliances,
    modelSerialNumber: 'MW-2020-1000W',
    dateCreated: new Date('2022-08-05'),
    status: 'NR',
    group: '',
    insuredsQuote: 110,
    ourquote: 100,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 23,
    name: 'Cloud Storage',
    category: ItemCategory.Other,
    modelSerialNumber: 'CS-2022-1TB',
    dateCreated: new Date('2022-08-06'),
    status: 'VPOL',
    group: '',
    insuredsQuote: 110,
    ourquote: 100,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 24,
    name: 'Office Plants',
    category: ItemCategory.Supplies,
    modelSerialNumber: null,
    dateCreated: new Date('2022-08-07'),
    status: 'NR',
    group: '',
    insuredsQuote: 160,
    ourquote: 150,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 25,
    name: 'Wireless Headphones',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'WH-2023-NOISE',
    dateCreated: new Date('2022-08-08'),
    status: 'RS',
    group: '',
    insuredsQuote: 220,
    ourquote: 200,
    receiptPhotoUrl: 'https://example.com/receipts/headphones2023.jpg',
    ourquoteLink: null,
  },
  {
    id: 26,
    name: 'Air Purifier',
    category: ItemCategory.Appliances,
    modelSerialNumber: 'AP-2022-HEPA',
    dateCreated: new Date('2022-08-09'),
    status: 'NR',
    group: '',
    insuredsQuote: 200,
    ourquote: 180,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 27,
    name: 'Presentation Clicker',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'PC-2021-LASER',
    dateCreated: new Date('2022-08-10'),
    status: 'RS',
    group: '',
    insuredsQuote: 35,
    ourquote: 30,
    receiptPhotoUrl: 'https://example.com/receipts/clicker2021.jpg',
    ourquoteLink: null,
  },
  {
    id: 28,
    name: 'Standing Desk Converter',
    category: ItemCategory.Furniture,
    modelSerialNumber: 'SDC-2020-ADJ',
    dateCreated: new Date('2022-08-11'),
    status: 'NR',
    group: '',
    insuredsQuote: 275,
    ourquote: 250,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
  {
    id: 29,
    name: 'Webcam',
    category: ItemCategory.Electronics,
    modelSerialNumber: 'WC-2022-1080P',
    dateCreated: new Date('2022-08-12'),
    status: 'RS',
    group: '',
    insuredsQuote: 90,
    ourquote: 80,
    receiptPhotoUrl: 'https://example.com/receipts/webcam2022.jpg',
    ourquoteLink: null,
  },
  {
    id: 30,
    name: 'Water Dispenser',
    category: ItemCategory.Appliances,
    modelSerialNumber: 'WD-2019-COOL',
    dateCreated: new Date('2022-08-13'),
    status: 'NR',
    group: '',
    insuredsQuote: 175,
    ourquote: 160,
    receiptPhotoUrl: null,
    ourquoteLink: null,
  },
];
