import { ItemStatus, EvidenceType } from '@prisma/client';

export const clm003Items = [
  {
    name: 'Laptop',
    category: 'Electronics',
    modelSerialNumber: 'LT-2023-XPS15',
    description: 'Home office laptop',
    insuredsQuote: 2000,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'laptop.jpg',
        url: 'https://example.com/receipts/laptop.jpg',
      },
    ],
  },
  {
    name: 'Office Desk',
    category: 'Furniture',
    modelSerialNumber: null,
    description: 'Home office desk',
    insuredsQuote: 500,
    ourQuote: 450,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Antivirus License',
    category: 'Digital',
    modelSerialNumber: 'AV-2023-PRO',
    description: 'Digital software license',
    insuredsQuote: null,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.PENDING,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'antivirus.jpg',
        url: 'https://example.com/receipts/antivirus.jpg',
      },
    ],
  },
  {
    name: 'Smartphone',
    category: 'Electronics',
    modelSerialNumber: 'SM-G-S23-ULTRA',
    description: 'Mobile phone',
    insuredsQuote: 1600,
    ourQuote: 1600,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'smartphone.jpg',
        url: 'https://example.com/receipts/smartphone.jpg',
      },
    ],
  },
  {
    name: 'Groceries',
    category: 'Food',
    modelSerialNumber: null,
    description: 'Food items',
    insuredsQuote: 155,
    ourQuote: null,
    condition: 'N/A',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Area Rug',
    category: 'Decor',
    modelSerialNumber: null,
    description: 'Loungeroom rug',
    insuredsQuote: 500,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Coffee Maker',
    category: 'Appliances',
    modelSerialNumber: 'CM-2023-DELUXE',
    description: 'Kitchen appliance',
    insuredsQuote: 300.75,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'coffeemaker.jpg',
        url: 'https://example.com/receipts/coffeemaker.jpg',
      },
    ],
  },
  {
    name: 'Office Chair',
    category: 'Furniture',
    modelSerialNumber: 'OC-2023-ERGO',
    description: 'Ergonomic office chair',
    insuredsQuote: 400,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Printer',
    category: 'Electronics',
    modelSerialNumber: 'PR-2023-LASER',
    description: 'Laser printer',
    insuredsQuote: null,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.PENDING,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'printer.jpg',
        url: 'https://example.com/receipts/printer.jpg',
      },
    ],
  },
  {
    name: 'Bookshelf',
    category: 'Furniture',
    modelSerialNumber: null,
    description: 'Bedroom bookshelf',
    insuredsQuote: 180,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Microwave',
    category: 'Appliances',
    modelSerialNumber: 'MW-2023-SMART',
    description: 'Kitchen microwave',
    insuredsQuote: 250,
    ourQuote: 250,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'microwave.jpg',
        url: 'https://example.com/receipts/microwave.jpg',
      },
    ],
  },
  {
    name: 'Dining Table',
    category: 'Furniture',
    modelSerialNumber: null,
    description: 'Dining room furniture',
    insuredsQuote: 750,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Vacuum Cleaner',
    category: 'Appliances',
    modelSerialNumber: 'VC-2023-ROBOT',
    description: 'Robot vacuum',
    insuredsQuote: null,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.PENDING,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'vacuum.jpg',
        url: 'https://example.com/receipts/vacuum.jpg',
      },
    ],
  },
  {
    name: 'Television',
    category: 'Electronics',
    modelSerialNumber: 'TV-2023-4K',
    description: '4K TV',
    insuredsQuote: 1200,
    ourQuote: 900,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [
      {
        type: EvidenceType.RECEIPT,
        filename: 'television.jpg',
        url: 'https://example.com/receipts/television.jpg',
      },
    ],
  },
  {
    name: 'Blender',
    category: 'Appliances',
    modelSerialNumber: 'BL-2023-PRO',
    description: 'Kitchen blender',
    insuredsQuote: 120,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Curtains',
    category: 'Decor',
    modelSerialNumber: null,
    description: 'Window curtains',
    insuredsQuote: 150,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Car Battery',
    category: 'Auto',
    modelSerialNumber: 'CB-2023-12V',
    description: 'Garage car battery',
    insuredsQuote: 200,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Bath towel',
    category: 'Bath',
    modelSerialNumber: '',
    description: 'Bathroom towel',
    insuredsQuote: 150,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Leather Jacket',
    category: 'Clothing',
    modelSerialNumber: null,
    description: 'Wardrobe leather jacket',
    insuredsQuote: 300,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Insurance Papers',
    category: 'Documents',
    modelSerialNumber: null,
    description: 'Important documents',
    insuredsQuote: null,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.PENDING,
    evidence: [],
  },
  {
    name: 'Lawn Mower',
    category: 'Garden',
    modelSerialNumber: 'LM-2023-ELECTRIC',
    description: 'Electric lawn mower',
    insuredsQuote: 600,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Lego Toys',
    category: 'Kids',
    modelSerialNumber: 'BC-2023-SAFE',
    description: 'Children toys',
    insuredsQuote: 400,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Miscellaneous Items Box',
    category: 'Other',
    modelSerialNumber: null,
    description: 'Storage box with misc items',
    insuredsQuote: 200,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Dog Bed',
    category: 'Pets',
    modelSerialNumber: null,
    description: 'Pet supplies',
    insuredsQuote: 80,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Tennis Racket',
    category: 'Recreation',
    modelSerialNumber: 'TR-2023-PRO',
    description: 'Sports equipment',
    insuredsQuote: 250,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Storage Cabinet',
    category: 'Storage',
    modelSerialNumber: null,
    description: 'Garage storage',
    insuredsQuote: 350,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Cleaning Supplies Set',
    category: 'Supplies',
    modelSerialNumber: null,
    description: 'Laundry room supplies',
    insuredsQuote: 120,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
  {
    name: 'Power Drill',
    category: 'Tools',
    modelSerialNumber: 'PD-2023-18V',
    description: 'Workshop power tool',
    insuredsQuote: 180,
    ourQuote: null,
    condition: 'Good',
    status: ItemStatus.AWAITING_QUOTES,
    evidence: [],
  },
];
